### ISSUE TITLE
OS X Yosemite 에서 build 문제

### ISSUE THREAD

**Issue by whchoi83** [naver/arcus-zookeeper#1]
본 이슈는 https://github.com/naver/arcus/issues/5 이슈와 관련 있습니다.

zookeeper [issue](https://issues.apache.org/jira/browse/ZOOKEEPER-2049):[commit](https://github.com/apache/zookeeper/commit/be2037eec138dbc993d2365a2dbd336acb1d60db) 로 보고되어 해결된 문제입니다. 해당 내용을 patch 하면 정상 build 됩니다.

**Comment by jhpark816** [comment]
patch 적용 되었음 - https://github.com/naver/arcus-zookeeper/commit/97b5aebae9900c9e9edcc24204b7a30ff1b03723
