### ISSUE TITLE
compile error of arcus-3.5.8 branch  

### ISSUE THREAD

**Issue by computerphilosopher** [naver/arcus-zookeeper#20]
centos7, gcc 4.8.5 환경에서 arcus-3.5.8 클라이언트 코드를 컴파일 할 경우 다음과 같은 컴파일 에러가 발생한다.

```
src/zookeeper.c: In function 'zookeeper_change_ensemble':
src/zookeeper.c:5264:13: error: ISO C90 forbids mixed declarations and code [-Werror=declaration-after-statement]
             char *temp = zh->hostname;
             ^
```

Makefile.am 파일에서 -Wdeclaration-after-statement 플래그를 삭제하면 정상적으로 컴파일 된다.

macOS, LLVM 10.0.1 환경에서는 플래그를 삭제하지 않아도 컴파일 되는 것으로 보아 gcc 버전에 관련된 이슈로 보인다.

**Comment by jhpark816** [comment]
@computerphilosopher 
declaration을 먼저 하도록 수정하면 되니, PR 보내주세요.
